### ISSUE TITLE
Library Request is Depreacted

### ISSUE THREAD

**Issue by ghostmech007** [forrest79/StaticNginxGallery#3]
```
ghostmech007@thevault:StaticNginxGallery$ npm install
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /opt/StaticNginxGallery/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh /tmp/postinstall-5da776b8.sh
npm ERR! Building: /usr/bin/node /opt/StaticNginxGallery/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/usr/bin/node',
npm ERR! gyp verb cli   '/opt/StaticNginxGallery/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@18.7.0 | linux | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb find Python Python is not set from command line or npm configuration
npm ERR! gyp verb find Python Python is not set from environment variable PYTHON
npm ERR! gyp verb find Python checking if "python3" can be used
npm ERR! gyp verb find Python - executing "python3" to get executable path
npm ERR! gyp verb find Python - executable path is "/usr/bin/python3"
npm ERR! gyp verb find Python - executing "/usr/bin/python3" to get version
npm ERR! gyp verb find Python - version is "3.9.2"
npm ERR! gyp info find Python using Python version 3.9.2 found at "/usr/bin/python3"
npm ERR! gyp verb get node dir no --target version specified, falling back to host node version: 18.7.0
npm ERR! gyp verb command install [ '18.7.0' ]
npm ERR! gyp verb install input version string "18.7.0"
npm ERR! gyp verb install installing version: 18.7.0
npm ERR! gyp verb install --ensure was passed, so won't reinstall if already installed
npm ERR! gyp verb install version is already installed, need to check "installVersion"
npm ERR! gyp verb got "installVersion" 9
npm ERR! gyp verb needs "installVersion" 9
npm ERR! gyp verb install version is good
npm ERR! gyp verb get node dir target node version installed: 18.7.0
npm ERR! gyp verb build dir attempting to create "build" dir: /opt/StaticNginxGallery/node_modules/node-sass/build
npm ERR! gyp verb build dir "build" dir needed to be created? Yes
npm ERR! gyp verb build/config.gypi creating config file
npm ERR! gyp verb build/config.gypi writing out config file: /opt/StaticNginxGallery/node_modules/node-sass/build/config.gypi
npm ERR! gyp verb config.gypi checking for gypi file: /opt/StaticNginxGallery/node_modules/node-sass/config.gypi
npm ERR! gyp verb common.gypi checking for gypi file: /opt/StaticNginxGallery/node_modules/node-sass/common.gypi
npm ERR! gyp verb gyp gyp format was not specified; forcing "make"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/opt/StaticNginxGallery/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/opt/StaticNginxGallery/node_modules/node-sass/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/opt/StaticNginxGallery/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/ghostmech007/.cache/node-gyp/18.7.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/ghostmech007/.cache/node-gyp/18.7.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/opt/StaticNginxGallery/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/ghostmech007/.cache/node-gyp/18.7.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/opt/StaticNginxGallery/node_modules/node-sass',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp verb command build []
npm ERR! gyp verb build type Release
npm ERR! gyp verb architecture x64
npm ERR! gyp verb node dev dir /home/ghostmech007/.cache/node-gyp/18.7.0
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: not found: make
npm ERR! gyp ERR! stack     at getNotFoundError (/opt/StaticNginxGallery/node_modules/which/which.js:10:17)
npm ERR! gyp ERR! stack     at /opt/StaticNginxGallery/node_modules/which/which.js:57:18
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at step (/opt/StaticNginxGallery/node_modules/which/which.js:54:21)
npm ERR! gyp ERR! stack     at /opt/StaticNginxGallery/node_modules/which/which.js:71:22
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at subStep (/opt/StaticNginxGallery/node_modules/which/which.js:69:33)
npm ERR! gyp ERR! stack     at /opt/StaticNginxGallery/node_modules/which/which.js:80:22
npm ERR! gyp ERR! stack     at /opt/StaticNginxGallery/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /opt/StaticNginxGallery/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! System Linux 5.10.0-16-amd64
npm ERR! gyp ERR! command "/usr/bin/node" "/opt/StaticNginxGallery/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /opt/StaticNginxGallery/node_modules/node-sass
npm ERR! gyp ERR! node -v v18.7.0
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ghostmech007/.npm/_logs/2022-08-16T16_23_53_144Z-debug-0.log
ghostmech007@thevault:StaticNginxGallery$
```

Apparently these libraries aren't supported anymore? Or am I missing something?

har-validator@5.1.5: this library is no longer supported
uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

**Comment by ghostmech007** [comment]
Whelp I'm dumb.

**Comment by ghostmech007** [comment]
Okay so install make fixed the problem before but now I'm running into this

```
[root@thevault:/opt/StaticNginxGallery/config]# npm run build config.yml --allow-root --unsafe-perm=true

> build
> node ./src/cli.mjs

node:fs:594
  handleErrorFromBinding(ctx);
  ^

Error: EACCES: permission denied, open '/etc/nginx/sites-available/static-nginx-gallery'
    at Object.openSync (node:fs:594:3)
    at Object.writeFileSync (node:fs:2207:35)
    at file:///opt/StaticNginxGallery/src/cli.mjs:232:4
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/etc/nginx/sites-available/static-nginx-gallery'
}
```

Which as far as I can tell is a permissions issues but i'm running as root and even put in flags to allow unsafe perms.   Any advice?

**Comment by ghostmech007** [comment]
Nevermind figured it out. Had to remove the failed files from the nginx directories. Issue closed.
